[package]
name = "clutch"
version = "0.1.0"
authors = ["Goran Peretin <goran.peretin@gmail.com>"]

[dependencies]
hipchat-client = { path = "../hipchat-client" }
chrono = "0.4"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"